branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.16"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libhunspell-1.3-0 libhunspell-dev 
  - echo "use Test::Text;just_check( 'txt','/usr/share/hunspell' );" > just_check.t
install: cpanm  ExtUtils::PkgConfig Test::Text TAP::Harness
script: perl -MTAP::Harness -e 'use utf8; my $harness = TAP::Harness->new( { verbosity => 0} ); die "FAIL" if  $harness->runtests( "just_check.t" )->failed;'

