#!/bin/bash

pandoc -s --reference-docx=../utils/plantilla.docx  \
       -o aprendepython.docx ../aprendepython.txt 00.prologo.md 01.empezar.md  \
       02.datos.md 03.logica.md 04.componiendo.md 05.identificando.md 06.sinpilas.md \
       07.entendiendo.md
   
