#!/bin/bash



pandoc -S --toc --epub-metadata=../metadata.xml --epub-stylesheet=../aprendepython.css \
       -o aprendepython.epub ../aprendepython.txt  01.empezar.md  \
       02.datos.md 03.logica.md 04.componiendo.md 05.identificando.md 06.sinpilas.md
   



