#!/bin/bash

mkdir -p html # It creates the directory if it does not exist
cp ../aprendepython.css html
rm aprendepython.html
for fichero in $( ls *.md)
do
    #echo ${fichero}
    pandoc -f markdown -s -t html -c aprendepython.css -o html/${fichero} ${fichero} 
    cat "html/$fichero" >> aprendepython.html
done

sed -i '1{
    h
    r include.css
    D
}
2{
    x
    G
    }' html/*.html

sed -i 's/..\/img/img/g' html/*.html

