#!/bin/bash

# Cambia la plantilla de latex al directorio donde esté
DIR=`pwd`
pandoc -V language=spanish -V lang=spanish \
    -V author='JJ Merelo' -V title='Introducción a Python'\
    -V documentclass=book\
    -S --latex-engine=xelatex  \
    -o aprende-python.pdf \
    01.empezar.md  02.datos.md 03.logica.md 04.componiendo.md  --toc



